import { POLICIES } from "../utils/constants/policies.js";

export const rolePolicyMap = {
  Admin: [POLICIES.USER_VIEW_ALL, POLICIES.USER_DELETE, POLICIES.BOOK_VIEW, POLICIES.LOAN_CREATE, POLICIES.LOAN_RETURN, POLICIES.LOAN_VIEW],
  User: [POLICIES.USER_VIEW_SELF, POLICIES.BOOK_VIEW, POLICIES.LOAN_CREATE, POLICIES.LOAN_RETURN, POLICIES.LOAN_VIEW],
  librarian: [POLICIES.BOOK_VIEW, POLICIES.LOAN_CREATE, POLICIES.LOAN_RETURN, POLICIES.LOAN_VIEW],
  member: [POLICIES.BOOK_VIEW, POLICIES.LOAN_CREATE, POLICIES.LOAN_RETURN, POLICIES.LOAN_VIEW]
};
