export const POLICIES = {
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_DELETE: "USER_DELETE",
  BOOK_VIEW: "BOOK_VIEW",
  LOAN_CREATE: "LOAN_CREATE",
  LOAN_RETURN: "LOAN_RETURN",
  LOAN_VIEW: "LOAN_VIEW"
};
